auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Cloudislife's Blog”
title: Cloudislife's blog
description: 
url: http://cloudislife.github.io/blog
feed: /atom.xml
author_info: <a href="http://cloudislife.github.io/blog">Cloudislife</a>
