auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Cloudislife
url: http://cloudislife.github.io
feed: /atom.xml
author_info: <a href="http://cloudislife.github.io/">Cloudislife</a>
